
INSERT INTO MACCHINA(CODICE, NOME, NOTE) VALUES('MA-047', NULL, NULL)
INSERT INTO MACCHINA(CODICE, NOME, NOTE) VALUES('MA-081', NULL, NULL)
INSERT INTO MACCHINA(CODICE, NOME, NOTE) VALUES('MA277B', NULL, NULL)

INSERT INTO MQTTDEVICE(MACCHINA_CODICE, TOPIC) VALUES('MA-047', 'v1/devices/ma-047/telemetry')
INSERT INTO MQTTDEVICE(MACCHINA_CODICE, TOPIC) VALUES('MA-081', 'v1/devices/ma-081/telemetry')

INSERT INTO OPCUADEVICE(MACCHINA_CODICE, IPADDRESS, TCPPORT) VALUES('MA277B', '192.168.220.1', '4840')
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 5, 4, '17', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 0, 4, '11', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 4, 4, '15', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 6, 4, '16', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 3, 4, '14', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 8, 4, '19', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 7, 4, '18', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 2, 4, '13', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
INSERT INTO OPCUANODE(OPCUADEVICE_ID, CATEGORIAVARIABILEPRODUZIONE, NAMESPACEINDEX, NODEIDENTIFIER, OPCUANODES_ORDER) SELECT ID, 1, 4, '12', 1 FROM OPCUADEVICE WHERE MACCHINA_CODICE LIKE 'MA277B'
